route:
  receiver: 'alert-receiver'
  group_by: ['category', 'instance', 'severity']
  group_wait: 10s
  group_interval: 5s
  repeat_interval: 15m

receivers:
  - name: 'alert-receiver'
    webhook_configs:
        - url: 'http://100.107.42.82:3456/webhook/prometheus'
          send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal:
      - instance
      - category
